name: api

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - env:
        NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        cd tests
        python benchmark.py

    - uses: actions/upload-artifact@v4
      with:
        name: reports
        path: |
          reports/comprehensive_benchmark_report.json
          reports/model_performance.db
          reports/*.html
        retention-days: 30

    - uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        text: benchmark completed
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}

