name: notebook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: |
        python -m pip install --upgrade pip
        pip install nbformat jupyter

    - id: repair
      run: python validate.py

    - if: failure() && steps.repair.outcome == 'failure'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.ipynb
        git commit -m "repair" || exit 0
        git push
